### ISSUE TITLE
[PA Review] Project Proposal

### ISSUE THREAD

**Issue by niartenyaw** [dchen323/InstaFriends#1]
Great work on your proposal! Please find my feedback below. You will need to incorporate these changes before you begin coding on Tuesday after A06. Feel free to work on this today so you're ready to hit the ground running tomorrow!

## DB Schema

Looks great! 👍 

## API Endpoints

- [x] Remember all of the resource names should be plural
- [x] Instead of `GET /api/user/:id/picture/:id - returns the picture information`, you could have `GET /api/users/:user_id/pictures` which returns all the pictures for that user (in addition to `GET /api/pictures` for the feed).
- [x] You won't need `GET /api/picture/:id/comments - returns the comments for a picture` since the comments should be included when the picture itself is fetched (whether on the show or index since a photo is never shown without comments).
- [x] You don't need to nest `DELETE /api/picture/:id/comment/:id - deletes a comment` since you'll already have the `comment_id`.

## State Shape

Looks good!

- [x] You'll want to have the keys in your state be in camelCase. It'll make your life way easier.

## Frontend Routes

- [x] For `/user/:userId/pictures/new - create a new picture to share`, you don't necessarily have to nest this under the current user since you'll always know who that is!

## Component Hierarchy & Wireframes

- [x] Can you potentially reuse the `PhotoIndex` for the `PhotoFeed`?
- [x] There probably won't be a `LikeIndex`, you'll just need your `LikeButton`.

**Comment by dchen323** [comment]
* added PATCH /api/pictures/:id - edit a picture caption to picture routes
* added edit and delete buttons for pictures
