### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by dchen323** [dchen323/InstaFriends#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by dchen323** [comment]
@niartenyaw Hi, Aaron. I finished adding seed data and should be ready for the issues checklist.

**Comment by niartenyaw** [comment]
Looks great! See below:

# User Auth

## Functionality

- [x] The main button with logo should link to `/`

### Before Login

- [X] The `/login` page should not display a `Log In` button in the navbar. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
- [X] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [X] Can sign up a user
- [X] Can sign out a user
- [X] Can sign in as a user
- [X] Can't sign up with the same username
- [X] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] All navlinks and buttons should `cursor: pointer` on hover
- [x] The submit button should be clear and probably have some hover effect
- [x] Any links to the other `SessionForm` should be very apparent that they are links
- [x] Check the padding everywhere (buttons, inputs, nav, form), this is a problem in almost every component
- [x] When errors are displayed, the input boxes should not move

**Comment by dchen323** [comment]
@niartenyaw Hi Aaron, I fixed the errors(input boxes do not move on error messages, fixed reroute on random url, and error clearing.

**Comment by niartenyaw** [comment]
@dchen323 awesome, looks great! You can close this issue!
