### ISSUE TITLE
PA Review: User Profile/Picture

### ISSUE THREAD

**Issue by dchen323** [dchen323/InstaFriends#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by niartenyaw** [comment]
Nice job!

- [x] It seems like some of the images are stretched. You may want to experiment with ways of making different images fit into the same sized container.
- [x] The background color should be gray
- [x] Getting some errors on uploading an image
