### ISSUE TITLE
PA Review: Comments

### ISSUE THREAD

**Issue by dchen323** [dchen323/InstaFriends#5]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by niartenyaw** [comment]
Sweet!

- [x] The comment text area looks really big, but I can't click into all of it to start typing.
- [x] Can you add a button to remove comments?

**Comment by dchen323** [comment]
@niartenyaw Hey Aaron, I finished these implementations.
